---
title: "Lab Week 8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Load the packages
```{r echo=FALSE, message=FALSE}
library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)

```

###Column graph of Texas Oil Spills
```{r}
oil_spills <- read_csv("oil_spills.csv")

df <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` < 2017) %>% 
  group_by(`Accident Year`) %>% 
  summarise(Loss = sum(`Net Loss (Barrels)`)) #Summarise by group above

colnames(df) <- c("Year", "Loss")

ggplot(df, aes(x = Year, y = Loss)) +
  geom_col()

```

### Leaflet plot of spill locations in TX in 2016
```{r}
df_loc <- oil_spills %>% 
  filter(`Accident State` =="TX", `Accident Year` == 2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)

colnames(df_loc) <- c("latitude", "longitude", "net_loss")

oil_sf <- st_as_sf(df_loc, coords = c("longitude", "latitude"), crs = 4326)

leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers()
```

### tmap plot with TX state shapefile
```{r}
states <- st_read(dsn = ".", layer= "states")

tex_border <- states %>% 
  filter(STATE_NAME == "Texas") %>% 
  st_transform(4326)

plot(tex_border)

tm_shape(tex_border) +
  tm_polygons() +
  tm_shape(oil_sf) +
  tm_dots(size = 0.3)
```

### convert to spatial point patterns (combo of point data and bounding window)
##we have to convert this to point pattern data to be able to do this outside of sf
```{r}
spill_sp <- as(oil_sf, "Spatial")
spill_ppp <- as(spill_sp, "ppp")

tx_sp <- as(tex_border, "Spatial")
tex_owin <- as(tx_sp, "owin")

all_ppp <- ppp(spill_ppp$x, spill_ppp$y, window = tex_owin)
```

